const
  WLR_VERSION_STR* = "0.15.1"
  WLR_VERSION_MAJOR* = 0
  WLR_VERSION_MINOR* = 15
  WLR_VERSION_MICRO* = 1
  WLR_VERSION_NUM* = ((WLR_VERSION_MAJOR shl 16) or (WLR_VERSION_MINOR shl 8) or WLR_VERSION_MICRO)
